import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "@/pages/layout/Navbar";
import Footer from "@/pages/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="flex flex-col items-center justify-center">
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        > */}
        <Navbar />
        {children}
        <Footer />

        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
